{"level":"error","message":"Uncaught exception Error: Oops!","stack":"Error: Oops!\n    at Object.<anonymous> (D:\\GIT3\\nodejs2021Q4-service\\src\\server.ts:6:7)\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n    at Module._compile (D:\\GIT3\\nodejs2021Q4-service\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\2BA0~1\\AppData\\Local\\Temp\\ts-node-dev-hook-8541614921001575.js:69:33)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\2BA0~1\\AppData\\Local\\Temp\\ts-node-dev-hook-8541614921001575.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\2BA0~1\\AppData\\Local\\Temp\\ts-node-dev-hook-8541614921001575.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\GIT3\\nodejs2021Q4-service\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)","timestamp":"2021-12-26 10:51:25:5125"}
{"level":"error","message":"Uncaught exception Error: Oops!","stack":"Error: Oops!\n    at Object.<anonymous> (D:\\GIT3\\nodejs2021Q4-service\\src\\app.ts:54:7)\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n    at Module._compile (D:\\GIT3\\nodejs2021Q4-service\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\2BA0~1\\AppData\\Local\\Temp\\ts-node-dev-hook-9465791806097414.js:69:33)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\2BA0~1\\AppData\\Local\\Temp\\ts-node-dev-hook-9465791806097414.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\2BA0~1\\AppData\\Local\\Temp\\ts-node-dev-hook-9465791806097414.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\GIT3\\nodejs2021Q4-service\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)","timestamp":"2021-12-26 10:52:17:5217"}
{"level":"error","message":"Uncaught exception Error: Oops!","stack":"Error: Oops!\n    at Object.<anonymous> (D:\\GIT3\\nodejs2021Q4-service\\src\\app.ts:56:7)\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n    at Module._compile (D:\\GIT3\\nodejs2021Q4-service\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\2BA0~1\\AppData\\Local\\Temp\\ts-node-dev-hook-9465791806097414.js:69:33)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\2BA0~1\\AppData\\Local\\Temp\\ts-node-dev-hook-9465791806097414.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\2BA0~1\\AppData\\Local\\Temp\\ts-node-dev-hook-9465791806097414.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\GIT3\\nodejs2021Q4-service\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)","timestamp":"2021-12-26 10:53:14:5314"}
